name=flowforge-pipeline
organization=com.example
package=$organization$.$name;format="norm,word"$
scala_version=2.13.14
flowforge_version=0.1.0-SNAPSHOT
cats_effect_version=3.5.4
spark_version=3.5.1
delta_version=3.3.2
