rules = [
  OrganizeImports,
  DisableSyntax,
  LeakingImplicitClassVal,
  NoAutoTupling,
  NoValInForComprehension,
  ProcedureSyntax,
  RemoveUnused
]

DisableSyntax.noVars = true
DisableSyntax.noThrows = false
DisableSyntax.noNulls = false
DisableSyntax.noReturns = true
DisableSyntax.noWhileLoops = true
DisableSyntax.noAsInstanceOf = false
DisableSyntax.noIsInstanceOf = true
DisableSyntax.noXml = true

OrganizeImports.removeUnused = true
OrganizeImports.groupedImports = Merge
