name: Reusable SBT Job

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '17'
      distribution:
        required: false
        type: string
        default: 'temurin'
      commands:
        required: true
        type: string
      cache-coursier:
        required: false
        type: boolean
        default: true

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sbt:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2 (pin). Ref: Apache Pekko pin example.

      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.x (pin)
        with:
          distribution: ${{ inputs.distribution }}
          java-version: ${{ inputs.java-version }}
          cache: 'sbt'

      - name: Cache Coursier (sbt/ivy/mill)
        if: ${{ inputs["cache-coursier"] }}
        uses: coursier/cache-action@4e2615869d13561d626ed48655e1a39e5b192b3c # v6.4.7 (pin)

      - name: Run SBT
        shell: bash
        run: sbt -batch ${{ inputs.commands }}
